package com.tj720.admin.dao.map;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.tj720.admin.base.dao.BaseDao;
import com.tj720.admin.model.CurationChapter;
import com.tj720.admin.model.CurationChapterExample;

public interface CurationChapterMapper extends BaseDao<CurationChapter>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_curation_chapter
     *
     * @mbggenerated Thu Oct 12 17:42:17 CST 2017
     */
    int countByExample(CurationChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_curation_chapter
     *
     * @mbggenerated Thu Oct 12 17:42:17 CST 2017
     */
    int deleteByExample(CurationChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_curation_chapter
     *
     * @mbggenerated Thu Oct 12 17:42:17 CST 2017
     */
    int insert(CurationChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_curation_chapter
     *
     * @mbggenerated Thu Oct 12 17:42:17 CST 2017
     */
    int insertSelective(CurationChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_curation_chapter
     *
     * @mbggenerated Thu Oct 12 17:42:17 CST 2017
     */
    List<CurationChapter> selectByExampleWithBLOBs(CurationChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_curation_chapter
     *
     * @mbggenerated Thu Oct 12 17:42:17 CST 2017
     */
    List<CurationChapter> selectByExample(CurationChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_curation_chapter
     *
     * @mbggenerated Thu Oct 12 17:42:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") CurationChapter record, @Param("example") CurationChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_curation_chapter
     *
     * @mbggenerated Thu Oct 12 17:42:17 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CurationChapter record, @Param("example") CurationChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_curation_chapter
     *
     * @mbggenerated Thu Oct 12 17:42:17 CST 2017
     */
    int updateByExample(@Param("record") CurationChapter record, @Param("example") CurationChapterExample example);
}