package com.tj720.admin.dao.map;

import com.tj720.admin.model.CulturalRelicInfo;
import com.tj720.admin.model.CulturalRelicInfoExample;
import com.tj720.admin.model.CulturalRelicPersonnelChange;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CulturalRelicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_info
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int countByExample(CulturalRelicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_info
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int deleteByExample(CulturalRelicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_info
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_info
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int insert(CulturalRelicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_info
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int insertSelective(CulturalRelicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_info
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    List<CulturalRelicInfo> selectByExample(CulturalRelicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_info
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    CulturalRelicInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_info
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") CulturalRelicInfo record, @Param("example") CulturalRelicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_info
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int updateByExample(@Param("record") CulturalRelicInfo record, @Param("example") CulturalRelicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_info
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int updateByPrimaryKeySelective(CulturalRelicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_info
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int updateByPrimaryKey(CulturalRelicInfo record);

	CulturalRelicInfo getByOrgId(String relicsBureauId);

	List<CulturalRelicInfo> getBaseInfo(@Param("orgId") String orgId,@Param("flag") String flag);

	void deleteInfo(@Param("orgId") String orgId,@Param("flag") String flag);

}