package com.tj720.admin.dao.map;

import com.tj720.admin.model.MipPictureSearchSet;
import com.tj720.admin.model.MipPictureSearchSetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MipPictureSearchSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_picture_search_set
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int countByExample(MipPictureSearchSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_picture_search_set
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByExample(MipPictureSearchSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_picture_search_set
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_picture_search_set
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insert(MipPictureSearchSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_picture_search_set
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insertSelective(MipPictureSearchSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_picture_search_set
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipPictureSearchSet> selectByExample(MipPictureSearchSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_picture_search_set
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    MipPictureSearchSet selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_picture_search_set
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") MipPictureSearchSet record, @Param("example") MipPictureSearchSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_picture_search_set
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExample(@Param("record") MipPictureSearchSet record, @Param("example") MipPictureSearchSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_picture_search_set
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeySelective(MipPictureSearchSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_picture_search_set
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKey(MipPictureSearchSet record);
}