package com.tj720.admin.model;

import java.util.Date;

public class MipPicture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.object_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String objectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.type_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.gs_No
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String gsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.url
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.pic_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer picWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.pic_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer picHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.is_main
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte isMain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb1
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String thumb1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb1_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thumb1Width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb1_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thumb1Height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb2
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String thumb2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb2_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thumb2Width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb2_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thumb2Height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb3
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String thumb3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb3_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thumb3Width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb3_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thumb3Height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb4
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String thumb4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb4_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thumb4Width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb4_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thumb4Height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb5
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String thumb5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb5_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thumb5Width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb5_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thumb5Height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb6
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String thumb6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb6_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thumb6Width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_picture.thumb6_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thumb6Height;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.id
     *
     * @return the value of mip_picture.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.id
     *
     * @param id the value for mip_picture.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.object_id
     *
     * @return the value of mip_picture.object_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.object_id
     *
     * @param objectId the value for mip_picture.object_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.type_id
     *
     * @return the value of mip_picture.type_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.type_id
     *
     * @param typeId the value for mip_picture.type_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.gs_No
     *
     * @return the value of mip_picture.gs_No
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getGsNo() {
        return gsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.gs_No
     *
     * @param gsNo the value for mip_picture.gs_No
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setGsNo(String gsNo) {
        this.gsNo = gsNo == null ? null : gsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.name
     *
     * @return the value of mip_picture.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.name
     *
     * @param name the value for mip_picture.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.url
     *
     * @return the value of mip_picture.url
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.url
     *
     * @param url the value for mip_picture.url
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.pic_width
     *
     * @return the value of mip_picture.pic_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getPicWidth() {
        return picWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.pic_width
     *
     * @param picWidth the value for mip_picture.pic_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setPicWidth(Integer picWidth) {
        this.picWidth = picWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.pic_height
     *
     * @return the value of mip_picture.pic_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getPicHeight() {
        return picHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.pic_height
     *
     * @param picHeight the value for mip_picture.pic_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setPicHeight(Integer picHeight) {
        this.picHeight = picHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.type
     *
     * @return the value of mip_picture.type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.type
     *
     * @param type the value for mip_picture.type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.is_main
     *
     * @return the value of mip_picture.is_main
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getIsMain() {
        return isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.is_main
     *
     * @param isMain the value for mip_picture.is_main
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setIsMain(Byte isMain) {
        this.isMain = isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.status
     *
     * @return the value of mip_picture.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.status
     *
     * @param status the value for mip_picture.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.sequence
     *
     * @return the value of mip_picture.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.sequence
     *
     * @param sequence the value for mip_picture.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.createTime
     *
     * @return the value of mip_picture.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.createTime
     *
     * @param createtime the value for mip_picture.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb1
     *
     * @return the value of mip_picture.thumb1
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getThumb1() {
        return thumb1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb1
     *
     * @param thumb1 the value for mip_picture.thumb1
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb1(String thumb1) {
        this.thumb1 = thumb1 == null ? null : thumb1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb1_width
     *
     * @return the value of mip_picture.thumb1_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThumb1Width() {
        return thumb1Width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb1_width
     *
     * @param thumb1Width the value for mip_picture.thumb1_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb1Width(Integer thumb1Width) {
        this.thumb1Width = thumb1Width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb1_height
     *
     * @return the value of mip_picture.thumb1_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThumb1Height() {
        return thumb1Height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb1_height
     *
     * @param thumb1Height the value for mip_picture.thumb1_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb1Height(Integer thumb1Height) {
        this.thumb1Height = thumb1Height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb2
     *
     * @return the value of mip_picture.thumb2
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getThumb2() {
        return thumb2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb2
     *
     * @param thumb2 the value for mip_picture.thumb2
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb2(String thumb2) {
        this.thumb2 = thumb2 == null ? null : thumb2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb2_width
     *
     * @return the value of mip_picture.thumb2_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThumb2Width() {
        return thumb2Width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb2_width
     *
     * @param thumb2Width the value for mip_picture.thumb2_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb2Width(Integer thumb2Width) {
        this.thumb2Width = thumb2Width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb2_height
     *
     * @return the value of mip_picture.thumb2_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThumb2Height() {
        return thumb2Height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb2_height
     *
     * @param thumb2Height the value for mip_picture.thumb2_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb2Height(Integer thumb2Height) {
        this.thumb2Height = thumb2Height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb3
     *
     * @return the value of mip_picture.thumb3
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getThumb3() {
        return thumb3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb3
     *
     * @param thumb3 the value for mip_picture.thumb3
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb3(String thumb3) {
        this.thumb3 = thumb3 == null ? null : thumb3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb3_width
     *
     * @return the value of mip_picture.thumb3_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThumb3Width() {
        return thumb3Width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb3_width
     *
     * @param thumb3Width the value for mip_picture.thumb3_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb3Width(Integer thumb3Width) {
        this.thumb3Width = thumb3Width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb3_height
     *
     * @return the value of mip_picture.thumb3_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThumb3Height() {
        return thumb3Height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb3_height
     *
     * @param thumb3Height the value for mip_picture.thumb3_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb3Height(Integer thumb3Height) {
        this.thumb3Height = thumb3Height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb4
     *
     * @return the value of mip_picture.thumb4
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getThumb4() {
        return thumb4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb4
     *
     * @param thumb4 the value for mip_picture.thumb4
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb4(String thumb4) {
        this.thumb4 = thumb4 == null ? null : thumb4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb4_width
     *
     * @return the value of mip_picture.thumb4_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThumb4Width() {
        return thumb4Width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb4_width
     *
     * @param thumb4Width the value for mip_picture.thumb4_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb4Width(Integer thumb4Width) {
        this.thumb4Width = thumb4Width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb4_height
     *
     * @return the value of mip_picture.thumb4_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThumb4Height() {
        return thumb4Height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb4_height
     *
     * @param thumb4Height the value for mip_picture.thumb4_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb4Height(Integer thumb4Height) {
        this.thumb4Height = thumb4Height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb5
     *
     * @return the value of mip_picture.thumb5
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getThumb5() {
        return thumb5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb5
     *
     * @param thumb5 the value for mip_picture.thumb5
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb5(String thumb5) {
        this.thumb5 = thumb5 == null ? null : thumb5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb5_width
     *
     * @return the value of mip_picture.thumb5_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThumb5Width() {
        return thumb5Width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb5_width
     *
     * @param thumb5Width the value for mip_picture.thumb5_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb5Width(Integer thumb5Width) {
        this.thumb5Width = thumb5Width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb5_height
     *
     * @return the value of mip_picture.thumb5_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThumb5Height() {
        return thumb5Height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb5_height
     *
     * @param thumb5Height the value for mip_picture.thumb5_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb5Height(Integer thumb5Height) {
        this.thumb5Height = thumb5Height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb6
     *
     * @return the value of mip_picture.thumb6
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getThumb6() {
        return thumb6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb6
     *
     * @param thumb6 the value for mip_picture.thumb6
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb6(String thumb6) {
        this.thumb6 = thumb6 == null ? null : thumb6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb6_width
     *
     * @return the value of mip_picture.thumb6_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThumb6Width() {
        return thumb6Width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb6_width
     *
     * @param thumb6Width the value for mip_picture.thumb6_width
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb6Width(Integer thumb6Width) {
        this.thumb6Width = thumb6Width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_picture.thumb6_height
     *
     * @return the value of mip_picture.thumb6_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThumb6Height() {
        return thumb6Height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_picture.thumb6_height
     *
     * @param thumb6Height the value for mip_picture.thumb6_height
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThumb6Height(Integer thumb6Height) {
        this.thumb6Height = thumb6Height;
    }
}