package com.tj720.admin.dao.map;

import com.tj720.admin.base.dao.BaseDao;
import com.tj720.admin.model.MipYearType;
import com.tj720.admin.model.MipYearTypeExample;
import com.tj720.mip.model.YearType;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MipYearTypeMapper extends BaseDao<MipYearType>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int countByExample(MipYearTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByExample(MipYearTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insert(MipYearType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insertSelective(MipYearType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipYearType> selectByExample(MipYearTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    MipYearType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") MipYearType record, @Param("example") MipYearTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExample(@Param("record") MipYearType record, @Param("example") MipYearTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeySelective(MipYearType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKey(MipYearType record);

	List<YearType> getEraList(String eon);
}