package com.tj720.admin.model;

public class GmCollectionRepairList {
	
	
	private String num;   // 序号
	
    public String getNum() {
		return num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_collection_repair_list.id
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_collection_repair_list.report_upload_id
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String reportUploadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_collection_repair_list.repair_collection_name
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String repairCollectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_collection_repair_list.level
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_collection_repair_list.collection_number
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String collectionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_collection_repair_list.reply_number
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String replyNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_collection_repair_list.repair_design_company
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String repairDesignCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_collection_repair_list.repair_company
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String repairCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_collection_repair_list.repair_outlay
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String repairOutlay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_collection_repair_list.id
     *
     * @return the value of gm_collection_repair_list.id
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_collection_repair_list.id
     *
     * @param id the value for gm_collection_repair_list.id
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_collection_repair_list.report_upload_id
     *
     * @return the value of gm_collection_repair_list.report_upload_id
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getReportUploadId() {
        return reportUploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_collection_repair_list.report_upload_id
     *
     * @param reportUploadId the value for gm_collection_repair_list.report_upload_id
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setReportUploadId(String reportUploadId) {
        this.reportUploadId = reportUploadId == null ? null : reportUploadId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_collection_repair_list.repair_collection_name
     *
     * @return the value of gm_collection_repair_list.repair_collection_name
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getRepairCollectionName() {
        return repairCollectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_collection_repair_list.repair_collection_name
     *
     * @param repairCollectionName the value for gm_collection_repair_list.repair_collection_name
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setRepairCollectionName(String repairCollectionName) {
        this.repairCollectionName = repairCollectionName == null ? null : repairCollectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_collection_repair_list.level
     *
     * @return the value of gm_collection_repair_list.level
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_collection_repair_list.level
     *
     * @param level the value for gm_collection_repair_list.level
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_collection_repair_list.collection_number
     *
     * @return the value of gm_collection_repair_list.collection_number
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getCollectionNumber() {
        return collectionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_collection_repair_list.collection_number
     *
     * @param collectionNumber the value for gm_collection_repair_list.collection_number
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setCollectionNumber(String collectionNumber) {
        this.collectionNumber = collectionNumber == null ? null : collectionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_collection_repair_list.reply_number
     *
     * @return the value of gm_collection_repair_list.reply_number
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getReplyNumber() {
        return replyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_collection_repair_list.reply_number
     *
     * @param replyNumber the value for gm_collection_repair_list.reply_number
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setReplyNumber(String replyNumber) {
        this.replyNumber = replyNumber == null ? null : replyNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_collection_repair_list.repair_design_company
     *
     * @return the value of gm_collection_repair_list.repair_design_company
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getRepairDesignCompany() {
        return repairDesignCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_collection_repair_list.repair_design_company
     *
     * @param repairDesignCompany the value for gm_collection_repair_list.repair_design_company
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setRepairDesignCompany(String repairDesignCompany) {
        this.repairDesignCompany = repairDesignCompany == null ? null : repairDesignCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_collection_repair_list.repair_company
     *
     * @return the value of gm_collection_repair_list.repair_company
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getRepairCompany() {
        return repairCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_collection_repair_list.repair_company
     *
     * @param repairCompany the value for gm_collection_repair_list.repair_company
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setRepairCompany(String repairCompany) {
        this.repairCompany = repairCompany == null ? null : repairCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_collection_repair_list.repair_outlay
     *
     * @return the value of gm_collection_repair_list.repair_outlay
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getRepairOutlay() {
        return repairOutlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_collection_repair_list.repair_outlay
     *
     * @param repairOutlay the value for gm_collection_repair_list.repair_outlay
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setRepairOutlay(String repairOutlay) {
        this.repairOutlay = repairOutlay == null ? null : repairOutlay.trim();
    }
}