package com.tj720.admin.model;

public class CCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.id
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.phone
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.password
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.company_name
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.category_name
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.province
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.city
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.address
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.zip_code
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.contacter
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String contacter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.sex
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.tel
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.email
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.fax
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.url
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.logo_src
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String logoSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.license_src
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String licenseSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.create_time
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.modify_time
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.status
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.is_enable
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private Integer isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.audit_msg
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String auditMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.account_type
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private Integer accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.login_counts
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private Integer loginCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.last_login_time
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.video_src
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String videoSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.description
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.id
     *
     * @return the value of c_company.id
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.id
     *
     * @param id the value for c_company.id
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.phone
     *
     * @return the value of c_company.phone
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.phone
     *
     * @param phone the value for c_company.phone
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.password
     *
     * @return the value of c_company.password
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.password
     *
     * @param password the value for c_company.password
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.company_name
     *
     * @return the value of c_company.company_name
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.company_name
     *
     * @param companyName the value for c_company.company_name
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.category_name
     *
     * @return the value of c_company.category_name
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.category_name
     *
     * @param categoryName the value for c_company.category_name
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.province
     *
     * @return the value of c_company.province
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.province
     *
     * @param province the value for c_company.province
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.city
     *
     * @return the value of c_company.city
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.city
     *
     * @param city the value for c_company.city
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.address
     *
     * @return the value of c_company.address
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.address
     *
     * @param address the value for c_company.address
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.zip_code
     *
     * @return the value of c_company.zip_code
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.zip_code
     *
     * @param zipCode the value for c_company.zip_code
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.contacter
     *
     * @return the value of c_company.contacter
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getContacter() {
        return contacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.contacter
     *
     * @param contacter the value for c_company.contacter
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setContacter(String contacter) {
        this.contacter = contacter == null ? null : contacter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.sex
     *
     * @return the value of c_company.sex
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.sex
     *
     * @param sex the value for c_company.sex
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.tel
     *
     * @return the value of c_company.tel
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.tel
     *
     * @param tel the value for c_company.tel
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.email
     *
     * @return the value of c_company.email
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.email
     *
     * @param email the value for c_company.email
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.fax
     *
     * @return the value of c_company.fax
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.fax
     *
     * @param fax the value for c_company.fax
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.url
     *
     * @return the value of c_company.url
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.url
     *
     * @param url the value for c_company.url
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.logo_src
     *
     * @return the value of c_company.logo_src
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getLogoSrc() {
        return logoSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.logo_src
     *
     * @param logoSrc the value for c_company.logo_src
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setLogoSrc(String logoSrc) {
        this.logoSrc = logoSrc == null ? null : logoSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.license_src
     *
     * @return the value of c_company.license_src
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getLicenseSrc() {
        return licenseSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.license_src
     *
     * @param licenseSrc the value for c_company.license_src
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setLicenseSrc(String licenseSrc) {
        this.licenseSrc = licenseSrc == null ? null : licenseSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.create_time
     *
     * @return the value of c_company.create_time
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.create_time
     *
     * @param createTime the value for c_company.create_time
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.modify_time
     *
     * @return the value of c_company.modify_time
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.modify_time
     *
     * @param modifyTime the value for c_company.modify_time
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.status
     *
     * @return the value of c_company.status
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.status
     *
     * @param status the value for c_company.status
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.is_enable
     *
     * @return the value of c_company.is_enable
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.is_enable
     *
     * @param isEnable the value for c_company.is_enable
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.audit_msg
     *
     * @return the value of c_company.audit_msg
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getAuditMsg() {
        return auditMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.audit_msg
     *
     * @param auditMsg the value for c_company.audit_msg
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setAuditMsg(String auditMsg) {
        this.auditMsg = auditMsg == null ? null : auditMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.account_type
     *
     * @return the value of c_company.account_type
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.account_type
     *
     * @param accountType the value for c_company.account_type
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.login_counts
     *
     * @return the value of c_company.login_counts
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public Integer getLoginCounts() {
        return loginCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.login_counts
     *
     * @param loginCounts the value for c_company.login_counts
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setLoginCounts(Integer loginCounts) {
        this.loginCounts = loginCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.last_login_time
     *
     * @return the value of c_company.last_login_time
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.last_login_time
     *
     * @param lastLoginTime the value for c_company.last_login_time
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setLastLoginTime(String lastLoginTime) {
        this.lastLoginTime = lastLoginTime == null ? null : lastLoginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.video_src
     *
     * @return the value of c_company.video_src
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getVideoSrc() {
        return videoSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.video_src
     *
     * @param videoSrc the value for c_company.video_src
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setVideoSrc(String videoSrc) {
        this.videoSrc = videoSrc == null ? null : videoSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.description
     *
     * @return the value of c_company.description
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.description
     *
     * @param description the value for c_company.description
     *
     * @mbggenerated Mon Sep 25 11:01:43 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}