package com.tj720.admin.model;

public class CurationChapterCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.id
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.chapter_id
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private String chapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.collection_id
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private String collectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.name
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.is_collection
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private String isCollection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.img_src
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private String imgSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.width
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private Integer width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.height
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.pos
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private Integer pos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.status
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.creat_time
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private String creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.modify_time
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_curation_chapter_collection.desc
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    private String desc;
    
    
    private String audioUrl;
    public String getAudioUrl() {
		return audioUrl;
	}
	public void setAudioUrl(String audioUrl) {
		this.audioUrl = audioUrl;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.id
     *
     * @return the value of ext_curation_chapter_collection.id
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.id
     *
     * @param id the value for ext_curation_chapter_collection.id
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.chapter_id
     *
     * @return the value of ext_curation_chapter_collection.chapter_id
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public String getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.chapter_id
     *
     * @param chapterId the value for ext_curation_chapter_collection.chapter_id
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setChapterId(String chapterId) {
        this.chapterId = chapterId == null ? null : chapterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.collection_id
     *
     * @return the value of ext_curation_chapter_collection.collection_id
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public String getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.collection_id
     *
     * @param collectionId the value for ext_curation_chapter_collection.collection_id
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setCollectionId(String collectionId) {
        this.collectionId = collectionId == null ? null : collectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.name
     *
     * @return the value of ext_curation_chapter_collection.name
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.name
     *
     * @param name the value for ext_curation_chapter_collection.name
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.is_collection
     *
     * @return the value of ext_curation_chapter_collection.is_collection
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public String getIsCollection() {
        return isCollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.is_collection
     *
     * @param isCollection the value for ext_curation_chapter_collection.is_collection
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setIsCollection(String isCollection) {
        this.isCollection = isCollection == null ? null : isCollection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.img_src
     *
     * @return the value of ext_curation_chapter_collection.img_src
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public String getImgSrc() {
        return imgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.img_src
     *
     * @param imgSrc the value for ext_curation_chapter_collection.img_src
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setImgSrc(String imgSrc) {
        this.imgSrc = imgSrc == null ? null : imgSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.width
     *
     * @return the value of ext_curation_chapter_collection.width
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.width
     *
     * @param width the value for ext_curation_chapter_collection.width
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.height
     *
     * @return the value of ext_curation_chapter_collection.height
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.height
     *
     * @param height the value for ext_curation_chapter_collection.height
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.pos
     *
     * @return the value of ext_curation_chapter_collection.pos
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public Integer getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.pos
     *
     * @param pos the value for ext_curation_chapter_collection.pos
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setPos(Integer pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.status
     *
     * @return the value of ext_curation_chapter_collection.status
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.status
     *
     * @param status the value for ext_curation_chapter_collection.status
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.creat_time
     *
     * @return the value of ext_curation_chapter_collection.creat_time
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.creat_time
     *
     * @param creatTime the value for ext_curation_chapter_collection.creat_time
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime == null ? null : creatTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.modify_time
     *
     * @return the value of ext_curation_chapter_collection.modify_time
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.modify_time
     *
     * @param modifyTime the value for ext_curation_chapter_collection.modify_time
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_curation_chapter_collection.desc
     *
     * @return the value of ext_curation_chapter_collection.desc
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_curation_chapter_collection.desc
     *
     * @param desc the value for ext_curation_chapter_collection.desc
     *
     * @mbggenerated Thu Oct 12 17:45:18 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}