package com.tj720.admin.model;

import java.util.Date;

public class MipAudio {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_audio.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_audio.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_audio.description
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_audio.type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_audio.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_audio.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_audio.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_audio.is_open
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte isOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_audio.url
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_audio.id
     *
     * @return the value of mip_audio.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_audio.id
     *
     * @param id the value for mip_audio.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_audio.name
     *
     * @return the value of mip_audio.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_audio.name
     *
     * @param name the value for mip_audio.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_audio.description
     *
     * @return the value of mip_audio.description
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_audio.description
     *
     * @param description the value for mip_audio.description
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_audio.type
     *
     * @return the value of mip_audio.type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_audio.type
     *
     * @param type the value for mip_audio.type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_audio.status
     *
     * @return the value of mip_audio.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_audio.status
     *
     * @param status the value for mip_audio.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_audio.sequence
     *
     * @return the value of mip_audio.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_audio.sequence
     *
     * @param sequence the value for mip_audio.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_audio.createTime
     *
     * @return the value of mip_audio.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_audio.createTime
     *
     * @param createtime the value for mip_audio.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_audio.is_open
     *
     * @return the value of mip_audio.is_open
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_audio.is_open
     *
     * @param isOpen the value for mip_audio.is_open
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setIsOpen(Byte isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_audio.url
     *
     * @return the value of mip_audio.url
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_audio.url
     *
     * @param url the value for mip_audio.url
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}