package com.tj720.admin.model;

import java.util.Date;

public class MipCollectionCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_collection_category.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_collection_category.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_collection_category.fc_counts
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer fcCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_collection_category.open_counts
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer openCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_collection_category.type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_collection_category.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_collection_category.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_collection_category.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_collection_category.short_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String shortName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_collection_category.id
     *
     * @return the value of mip_collection_category.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_collection_category.id
     *
     * @param id the value for mip_collection_category.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_collection_category.name
     *
     * @return the value of mip_collection_category.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_collection_category.name
     *
     * @param name the value for mip_collection_category.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_collection_category.fc_counts
     *
     * @return the value of mip_collection_category.fc_counts
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getFcCounts() {
        return fcCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_collection_category.fc_counts
     *
     * @param fcCounts the value for mip_collection_category.fc_counts
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setFcCounts(Integer fcCounts) {
        this.fcCounts = fcCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_collection_category.open_counts
     *
     * @return the value of mip_collection_category.open_counts
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getOpenCounts() {
        return openCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_collection_category.open_counts
     *
     * @param openCounts the value for mip_collection_category.open_counts
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setOpenCounts(Integer openCounts) {
        this.openCounts = openCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_collection_category.type
     *
     * @return the value of mip_collection_category.type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_collection_category.type
     *
     * @param type the value for mip_collection_category.type
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_collection_category.status
     *
     * @return the value of mip_collection_category.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_collection_category.status
     *
     * @param status the value for mip_collection_category.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_collection_category.sequence
     *
     * @return the value of mip_collection_category.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_collection_category.sequence
     *
     * @param sequence the value for mip_collection_category.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_collection_category.createTime
     *
     * @return the value of mip_collection_category.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_collection_category.createTime
     *
     * @param createtime the value for mip_collection_category.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_collection_category.short_name
     *
     * @return the value of mip_collection_category.short_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_collection_category.short_name
     *
     * @param shortName the value for mip_collection_category.short_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }
}