package com.tj720.admin.model;

import java.util.Date;

public class MipCuration {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.title
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.series_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String seriesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.series_num
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte seriesNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.from_date
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer fromDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.end_date
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.image1
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String image1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.image2
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String image2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.image3
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String image3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.image4
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String image4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.image5
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String image5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.image6
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String image6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.image7
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String image7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.image8
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String image8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.image9
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String image9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.image10
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String image10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.image11
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String image11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.image12
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String image12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.uid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.is_published
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte isPublished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.publish_time
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Long publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.main_image
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String mainImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.like_counts
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer likeCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.pid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.author
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_curation.audio
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String audio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.id
     *
     * @return the value of mip_curation.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.id
     *
     * @param id the value for mip_curation.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.title
     *
     * @return the value of mip_curation.title
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.title
     *
     * @param title the value for mip_curation.title
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.series_name
     *
     * @return the value of mip_curation.series_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getSeriesName() {
        return seriesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.series_name
     *
     * @param seriesName the value for mip_curation.series_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSeriesName(String seriesName) {
        this.seriesName = seriesName == null ? null : seriesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.series_num
     *
     * @return the value of mip_curation.series_num
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getSeriesNum() {
        return seriesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.series_num
     *
     * @param seriesNum the value for mip_curation.series_num
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSeriesNum(Byte seriesNum) {
        this.seriesNum = seriesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.from_date
     *
     * @return the value of mip_curation.from_date
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.from_date
     *
     * @param fromDate the value for mip_curation.from_date
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setFromDate(Integer fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.end_date
     *
     * @return the value of mip_curation.end_date
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.end_date
     *
     * @param endDate the value for mip_curation.end_date
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setEndDate(Integer endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.image1
     *
     * @return the value of mip_curation.image1
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getImage1() {
        return image1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.image1
     *
     * @param image1 the value for mip_curation.image1
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setImage1(String image1) {
        this.image1 = image1 == null ? null : image1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.image2
     *
     * @return the value of mip_curation.image2
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getImage2() {
        return image2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.image2
     *
     * @param image2 the value for mip_curation.image2
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setImage2(String image2) {
        this.image2 = image2 == null ? null : image2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.image3
     *
     * @return the value of mip_curation.image3
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getImage3() {
        return image3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.image3
     *
     * @param image3 the value for mip_curation.image3
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setImage3(String image3) {
        this.image3 = image3 == null ? null : image3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.image4
     *
     * @return the value of mip_curation.image4
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getImage4() {
        return image4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.image4
     *
     * @param image4 the value for mip_curation.image4
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setImage4(String image4) {
        this.image4 = image4 == null ? null : image4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.image5
     *
     * @return the value of mip_curation.image5
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getImage5() {
        return image5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.image5
     *
     * @param image5 the value for mip_curation.image5
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setImage5(String image5) {
        this.image5 = image5 == null ? null : image5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.image6
     *
     * @return the value of mip_curation.image6
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getImage6() {
        return image6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.image6
     *
     * @param image6 the value for mip_curation.image6
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setImage6(String image6) {
        this.image6 = image6 == null ? null : image6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.image7
     *
     * @return the value of mip_curation.image7
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getImage7() {
        return image7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.image7
     *
     * @param image7 the value for mip_curation.image7
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setImage7(String image7) {
        this.image7 = image7 == null ? null : image7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.image8
     *
     * @return the value of mip_curation.image8
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getImage8() {
        return image8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.image8
     *
     * @param image8 the value for mip_curation.image8
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setImage8(String image8) {
        this.image8 = image8 == null ? null : image8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.image9
     *
     * @return the value of mip_curation.image9
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getImage9() {
        return image9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.image9
     *
     * @param image9 the value for mip_curation.image9
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setImage9(String image9) {
        this.image9 = image9 == null ? null : image9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.image10
     *
     * @return the value of mip_curation.image10
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getImage10() {
        return image10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.image10
     *
     * @param image10 the value for mip_curation.image10
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setImage10(String image10) {
        this.image10 = image10 == null ? null : image10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.image11
     *
     * @return the value of mip_curation.image11
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getImage11() {
        return image11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.image11
     *
     * @param image11 the value for mip_curation.image11
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setImage11(String image11) {
        this.image11 = image11 == null ? null : image11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.image12
     *
     * @return the value of mip_curation.image12
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getImage12() {
        return image12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.image12
     *
     * @param image12 the value for mip_curation.image12
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setImage12(String image12) {
        this.image12 = image12 == null ? null : image12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.status
     *
     * @return the value of mip_curation.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.status
     *
     * @param status the value for mip_curation.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.sequence
     *
     * @return the value of mip_curation.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.sequence
     *
     * @param sequence the value for mip_curation.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.createTime
     *
     * @return the value of mip_curation.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.createTime
     *
     * @param createtime the value for mip_curation.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.uid
     *
     * @return the value of mip_curation.uid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.uid
     *
     * @param uid the value for mip_curation.uid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.is_published
     *
     * @return the value of mip_curation.is_published
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getIsPublished() {
        return isPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.is_published
     *
     * @param isPublished the value for mip_curation.is_published
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setIsPublished(Byte isPublished) {
        this.isPublished = isPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.publish_time
     *
     * @return the value of mip_curation.publish_time
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Long getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.publish_time
     *
     * @param publishTime the value for mip_curation.publish_time
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setPublishTime(Long publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.main_image
     *
     * @return the value of mip_curation.main_image
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getMainImage() {
        return mainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.main_image
     *
     * @param mainImage the value for mip_curation.main_image
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setMainImage(String mainImage) {
        this.mainImage = mainImage == null ? null : mainImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.like_counts
     *
     * @return the value of mip_curation.like_counts
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getLikeCounts() {
        return likeCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.like_counts
     *
     * @param likeCounts the value for mip_curation.like_counts
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setLikeCounts(Integer likeCounts) {
        this.likeCounts = likeCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.pid
     *
     * @return the value of mip_curation.pid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.pid
     *
     * @param pid the value for mip_curation.pid
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.author
     *
     * @return the value of mip_curation.author
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.author
     *
     * @param author the value for mip_curation.author
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_curation.audio
     *
     * @return the value of mip_curation.audio
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getAudio() {
        return audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_curation.audio
     *
     * @param audio the value for mip_curation.audio
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setAudio(String audio) {
        this.audio = audio == null ? null : audio.trim();
    }
}