package com.tj720.admin.model;

import java.util.ArrayList;
import java.util.List;

public class MipTourCollectionExample {

    protected int size;
    protected int startPage;


    public int getSize() {
        return size;
    }

    public void setSize(int size) {
        this.size = size;
    }

    public int getStartPage() {
        return startPage;
    }

    public void setStartPage(int startPage) {
        this.startPage = startPage;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    protected List<MipTourCollectionExample.Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    public MipTourCollectionExample() {
        oredCriteria = new ArrayList<MipTourCollectionExample.Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    public List<MipTourCollectionExample.Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    public void or(MipTourCollectionExample.Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    public MipTourCollectionExample.Criteria or() {
        MipTourCollectionExample.Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    public MipTourCollectionExample.Criteria createCriteria() {
        MipTourCollectionExample.Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    protected MipTourCollectionExample.Criteria createCriteriaInternal() {
        MipTourCollectionExample.Criteria criteria = new MipTourCollectionExample.Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<MipTourCollectionExample.Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<MipTourCollectionExample.Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<MipTourCollectionExample.Criterion> getAllCriteria() {
            return criteria;
        }

        public List<MipTourCollectionExample.Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new MipTourCollectionExample.Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new MipTourCollectionExample.Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new MipTourCollectionExample.Criterion(condition, value1, value2));
        }

        public MipTourCollectionExample.Criteria andIdIsNull() {
            addCriterion("id is null");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdIsNull() {
            addCriterion("tour_id is null");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdIsNotNull() {
            addCriterion("tour_id is not null");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdEqualTo(String value) {
            addCriterion("tour_id =", value, "topicId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdNotEqualTo(String value) {
            addCriterion("tour_id <>", value, "topicId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdGreaterThan(String value) {
            addCriterion("tour_id >", value, "topicId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdGreaterThanOrEqualTo(String value) {
            addCriterion("tour_id >=", value, "topicId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdLessThan(String value) {
            addCriterion("tour_id <", value, "topicId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdLessThanOrEqualTo(String value) {
            addCriterion("tour_id <=", value, "topicId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdLike(String value) {
            addCriterion("tour_id like", value, "topicId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdNotLike(String value) {
            addCriterion("tour_id not like", value, "topicId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdIn(List<String> values) {
            addCriterion("tour_id in", values, "topicId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdNotIn(List<String> values) {
            addCriterion("tour_id not in", values, "topicId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdBetween(String value1, String value2) {
            addCriterion("tour_id between", value1, value2, "topicId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andTopicIdNotBetween(String value1, String value2) {
            addCriterion("tour_id not between", value1, value2, "topicId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdIsNull() {
            addCriterion("collection_id is null");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdIsNotNull() {
            addCriterion("collection_id is not null");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdEqualTo(String value) {
            addCriterion("collection_id =", value, "collectionId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdNotEqualTo(String value) {
            addCriterion("collection_id <>", value, "collectionId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdGreaterThan(String value) {
            addCriterion("collection_id >", value, "collectionId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdGreaterThanOrEqualTo(String value) {
            addCriterion("collection_id >=", value, "collectionId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdLessThan(String value) {
            addCriterion("collection_id <", value, "collectionId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdLessThanOrEqualTo(String value) {
            addCriterion("collection_id <=", value, "collectionId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdLike(String value) {
            addCriterion("collection_id like", value, "collectionId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdNotLike(String value) {
            addCriterion("collection_id not like", value, "collectionId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdIn(List<String> values) {
            addCriterion("collection_id in", values, "collectionId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdNotIn(List<String> values) {
            addCriterion("collection_id not in", values, "collectionId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdBetween(String value1, String value2) {
            addCriterion("collection_id between", value1, value2, "collectionId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andCollectionIdNotBetween(String value1, String value2) {
            addCriterion("collection_id not between", value1, value2, "collectionId");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andSortIsNull() {
            addCriterion("sort is null");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andSortIsNotNull() {
            addCriterion("sort is not null");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andSortEqualTo(Integer value) {
            addCriterion("sort =", value, "sort");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andSortNotEqualTo(Integer value) {
            addCriterion("sort <>", value, "sort");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andSortGreaterThan(Integer value) {
            addCriterion("sort >", value, "sort");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("sort >=", value, "sort");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andSortLessThan(Integer value) {
            addCriterion("sort <", value, "sort");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("sort <=", value, "sort");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andSortIn(List<Integer> values) {
            addCriterion("sort in", values, "sort");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andSortNotIn(List<Integer> values) {
            addCriterion("sort not in", values, "sort");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("sort between", value1, value2, "sort");
            return (MipTourCollectionExample.Criteria) this;
        }

        public MipTourCollectionExample.Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("sort not between", value1, value2, "sort");
            return (MipTourCollectionExample.Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mip_topic_collection
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 08 15:42:19 CST 2018
     */
    public static class Criteria extends MipTourCollectionExample.GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
