package com.tj720.admin.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MipYearCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public MipYearCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryIsNull() {
            addCriterion("collections_category is null");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryIsNotNull() {
            addCriterion("collections_category is not null");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryEqualTo(String value) {
            addCriterion("collections_category =", value, "collectionsCategory");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryNotEqualTo(String value) {
            addCriterion("collections_category <>", value, "collectionsCategory");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryGreaterThan(String value) {
            addCriterion("collections_category >", value, "collectionsCategory");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("collections_category >=", value, "collectionsCategory");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryLessThan(String value) {
            addCriterion("collections_category <", value, "collectionsCategory");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryLessThanOrEqualTo(String value) {
            addCriterion("collections_category <=", value, "collectionsCategory");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryLike(String value) {
            addCriterion("collections_category like", value, "collectionsCategory");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryNotLike(String value) {
            addCriterion("collections_category not like", value, "collectionsCategory");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryIn(List<String> values) {
            addCriterion("collections_category in", values, "collectionsCategory");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryNotIn(List<String> values) {
            addCriterion("collections_category not in", values, "collectionsCategory");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryBetween(String value1, String value2) {
            addCriterion("collections_category between", value1, value2, "collectionsCategory");
            return (Criteria) this;
        }

        public Criteria andCollectionsCategoryNotBetween(String value1, String value2) {
            addCriterion("collections_category not between", value1, value2, "collectionsCategory");
            return (Criteria) this;
        }

        public Criteria andYearTypeIsNull() {
            addCriterion("year_type is null");
            return (Criteria) this;
        }

        public Criteria andYearTypeIsNotNull() {
            addCriterion("year_type is not null");
            return (Criteria) this;
        }

        public Criteria andYearTypeEqualTo(String value) {
            addCriterion("year_type =", value, "yearType");
            return (Criteria) this;
        }

        public Criteria andYearTypeNotEqualTo(String value) {
            addCriterion("year_type <>", value, "yearType");
            return (Criteria) this;
        }

        public Criteria andYearTypeGreaterThan(String value) {
            addCriterion("year_type >", value, "yearType");
            return (Criteria) this;
        }

        public Criteria andYearTypeGreaterThanOrEqualTo(String value) {
            addCriterion("year_type >=", value, "yearType");
            return (Criteria) this;
        }

        public Criteria andYearTypeLessThan(String value) {
            addCriterion("year_type <", value, "yearType");
            return (Criteria) this;
        }

        public Criteria andYearTypeLessThanOrEqualTo(String value) {
            addCriterion("year_type <=", value, "yearType");
            return (Criteria) this;
        }

        public Criteria andYearTypeLike(String value) {
            addCriterion("year_type like", value, "yearType");
            return (Criteria) this;
        }

        public Criteria andYearTypeNotLike(String value) {
            addCriterion("year_type not like", value, "yearType");
            return (Criteria) this;
        }

        public Criteria andYearTypeIn(List<String> values) {
            addCriterion("year_type in", values, "yearType");
            return (Criteria) this;
        }

        public Criteria andYearTypeNotIn(List<String> values) {
            addCriterion("year_type not in", values, "yearType");
            return (Criteria) this;
        }

        public Criteria andYearTypeBetween(String value1, String value2) {
            addCriterion("year_type between", value1, value2, "yearType");
            return (Criteria) this;
        }

        public Criteria andYearTypeNotBetween(String value1, String value2) {
            addCriterion("year_type not between", value1, value2, "yearType");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitIsNull() {
            addCriterion("collection_unit is null");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitIsNotNull() {
            addCriterion("collection_unit is not null");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitEqualTo(String value) {
            addCriterion("collection_unit =", value, "collectionUnit");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitNotEqualTo(String value) {
            addCriterion("collection_unit <>", value, "collectionUnit");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitGreaterThan(String value) {
            addCriterion("collection_unit >", value, "collectionUnit");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitGreaterThanOrEqualTo(String value) {
            addCriterion("collection_unit >=", value, "collectionUnit");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitLessThan(String value) {
            addCriterion("collection_unit <", value, "collectionUnit");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitLessThanOrEqualTo(String value) {
            addCriterion("collection_unit <=", value, "collectionUnit");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitLike(String value) {
            addCriterion("collection_unit like", value, "collectionUnit");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitNotLike(String value) {
            addCriterion("collection_unit not like", value, "collectionUnit");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitIn(List<String> values) {
            addCriterion("collection_unit in", values, "collectionUnit");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitNotIn(List<String> values) {
            addCriterion("collection_unit not in", values, "collectionUnit");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitBetween(String value1, String value2) {
            addCriterion("collection_unit between", value1, value2, "collectionUnit");
            return (Criteria) this;
        }

        public Criteria andCollectionUnitNotBetween(String value1, String value2) {
            addCriterion("collection_unit not between", value1, value2, "collectionUnit");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("city_id is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("city_id is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(String value) {
            addCriterion("city_id =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(String value) {
            addCriterion("city_id <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(String value) {
            addCriterion("city_id >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(String value) {
            addCriterion("city_id >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(String value) {
            addCriterion("city_id <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(String value) {
            addCriterion("city_id <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLike(String value) {
            addCriterion("city_id like", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotLike(String value) {
            addCriterion("city_id not like", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<String> values) {
            addCriterion("city_id in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<String> values) {
            addCriterion("city_id not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(String value1, String value2) {
            addCriterion("city_id between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(String value1, String value2) {
            addCriterion("city_id not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCountsIsNull() {
            addCriterion("counts is null");
            return (Criteria) this;
        }

        public Criteria andCountsIsNotNull() {
            addCriterion("counts is not null");
            return (Criteria) this;
        }

        public Criteria andCountsEqualTo(Integer value) {
            addCriterion("counts =", value, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsNotEqualTo(Integer value) {
            addCriterion("counts <>", value, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsGreaterThan(Integer value) {
            addCriterion("counts >", value, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("counts >=", value, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsLessThan(Integer value) {
            addCriterion("counts <", value, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsLessThanOrEqualTo(Integer value) {
            addCriterion("counts <=", value, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsIn(List<Integer> values) {
            addCriterion("counts in", values, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsNotIn(List<Integer> values) {
            addCriterion("counts not in", values, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsBetween(Integer value1, Integer value2) {
            addCriterion("counts between", value1, value2, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("counts not between", value1, value2, "counts");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNull() {
            addCriterion("sequence is null");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNotNull() {
            addCriterion("sequence is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceEqualTo(Integer value) {
            addCriterion("sequence =", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotEqualTo(Integer value) {
            addCriterion("sequence <>", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThan(Integer value) {
            addCriterion("sequence >", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThanOrEqualTo(Integer value) {
            addCriterion("sequence >=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThan(Integer value) {
            addCriterion("sequence <", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThanOrEqualTo(Integer value) {
            addCriterion("sequence <=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceIn(List<Integer> values) {
            addCriterion("sequence in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotIn(List<Integer> values) {
            addCriterion("sequence not in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceBetween(Integer value1, Integer value2) {
            addCriterion("sequence between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotBetween(Integer value1, Integer value2) {
            addCriterion("sequence not between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andYearSequenceIsNull() {
            addCriterion("year_sequence is null");
            return (Criteria) this;
        }

        public Criteria andYearSequenceIsNotNull() {
            addCriterion("year_sequence is not null");
            return (Criteria) this;
        }

        public Criteria andYearSequenceEqualTo(Integer value) {
            addCriterion("year_sequence =", value, "yearSequence");
            return (Criteria) this;
        }

        public Criteria andYearSequenceNotEqualTo(Integer value) {
            addCriterion("year_sequence <>", value, "yearSequence");
            return (Criteria) this;
        }

        public Criteria andYearSequenceGreaterThan(Integer value) {
            addCriterion("year_sequence >", value, "yearSequence");
            return (Criteria) this;
        }

        public Criteria andYearSequenceGreaterThanOrEqualTo(Integer value) {
            addCriterion("year_sequence >=", value, "yearSequence");
            return (Criteria) this;
        }

        public Criteria andYearSequenceLessThan(Integer value) {
            addCriterion("year_sequence <", value, "yearSequence");
            return (Criteria) this;
        }

        public Criteria andYearSequenceLessThanOrEqualTo(Integer value) {
            addCriterion("year_sequence <=", value, "yearSequence");
            return (Criteria) this;
        }

        public Criteria andYearSequenceIn(List<Integer> values) {
            addCriterion("year_sequence in", values, "yearSequence");
            return (Criteria) this;
        }

        public Criteria andYearSequenceNotIn(List<Integer> values) {
            addCriterion("year_sequence not in", values, "yearSequence");
            return (Criteria) this;
        }

        public Criteria andYearSequenceBetween(Integer value1, Integer value2) {
            addCriterion("year_sequence between", value1, value2, "yearSequence");
            return (Criteria) this;
        }

        public Criteria andYearSequenceNotBetween(Integer value1, Integer value2) {
            addCriterion("year_sequence not between", value1, value2, "yearSequence");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mip_year_category
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 09 11:14:20 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mip_year_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}