package com.tj720.admin.dao.map;

import com.tj720.admin.model.MipMuseumInfo;
import com.tj720.admin.model.MipMuseumInfoExample;
import com.tj720.admin.model.MipMuseumInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MipMuseumInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int countByExample(MipMuseumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByExample(MipMuseumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insert(MipMuseumInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insertSelective(MipMuseumInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipMuseumInfoWithBLOBs> selectByExampleWithBLOBs(MipMuseumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipMuseumInfo> selectByExample(MipMuseumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    MipMuseumInfoWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") MipMuseumInfoWithBLOBs record, @Param("example") MipMuseumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") MipMuseumInfoWithBLOBs record, @Param("example") MipMuseumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExample(@Param("record") MipMuseumInfo record, @Param("example") MipMuseumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeySelective(MipMuseumInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(MipMuseumInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_museum_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKey(MipMuseumInfo record);
}