package com.tj720.admin.model;

public class GmMuseumRegisterInfoWithBLOBs extends GmMuseumRegisterInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_museum_register_info.main_collection
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    private String mainCollection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_museum_register_info.base_display_content
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    private String baseDisplayContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_museum_register_info.collection_security
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    private String collectionSecurity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_museum_register_info.audience_security
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    private String audienceSecurity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_museum_register_info.mark
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_museum_register_info.city_opinion
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    private String cityOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_museum_register_info.province_opinion
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    private String provinceOpinion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_museum_register_info.main_collection
     *
     * @return the value of gm_museum_register_info.main_collection
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public String getMainCollection() {
        return mainCollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_museum_register_info.main_collection
     *
     * @param mainCollection the value for gm_museum_register_info.main_collection
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public void setMainCollection(String mainCollection) {
        this.mainCollection = mainCollection == null ? null : mainCollection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_museum_register_info.base_display_content
     *
     * @return the value of gm_museum_register_info.base_display_content
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public String getBaseDisplayContent() {
        return baseDisplayContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_museum_register_info.base_display_content
     *
     * @param baseDisplayContent the value for gm_museum_register_info.base_display_content
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public void setBaseDisplayContent(String baseDisplayContent) {
        this.baseDisplayContent = baseDisplayContent == null ? null : baseDisplayContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_museum_register_info.collection_security
     *
     * @return the value of gm_museum_register_info.collection_security
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public String getCollectionSecurity() {
        return collectionSecurity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_museum_register_info.collection_security
     *
     * @param collectionSecurity the value for gm_museum_register_info.collection_security
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public void setCollectionSecurity(String collectionSecurity) {
        this.collectionSecurity = collectionSecurity == null ? null : collectionSecurity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_museum_register_info.audience_security
     *
     * @return the value of gm_museum_register_info.audience_security
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public String getAudienceSecurity() {
        return audienceSecurity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_museum_register_info.audience_security
     *
     * @param audienceSecurity the value for gm_museum_register_info.audience_security
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public void setAudienceSecurity(String audienceSecurity) {
        this.audienceSecurity = audienceSecurity == null ? null : audienceSecurity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_museum_register_info.mark
     *
     * @return the value of gm_museum_register_info.mark
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_museum_register_info.mark
     *
     * @param mark the value for gm_museum_register_info.mark
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_museum_register_info.city_opinion
     *
     * @return the value of gm_museum_register_info.city_opinion
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public String getCityOpinion() {
        return cityOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_museum_register_info.city_opinion
     *
     * @param cityOpinion the value for gm_museum_register_info.city_opinion
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public void setCityOpinion(String cityOpinion) {
        this.cityOpinion = cityOpinion == null ? null : cityOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_museum_register_info.province_opinion
     *
     * @return the value of gm_museum_register_info.province_opinion
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public String getProvinceOpinion() {
        return provinceOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_museum_register_info.province_opinion
     *
     * @param provinceOpinion the value for gm_museum_register_info.province_opinion
     *
     * @mbggenerated Wed Aug 30 10:03:30 CST 2017
     */
    public void setProvinceOpinion(String provinceOpinion) {
        this.provinceOpinion = provinceOpinion == null ? null : provinceOpinion.trim();
    }
}