/**--单击事件备注信息--******/
try{
	$("[id='botton_1532072958474']").click(function(){
		/**--执行方法体-start--******/
			$.saveData(true);
		/**--执行方法体-end--******/
	});
}catch(e){}
/**--单击事件备注信息--******/
try{
	$("[id='botton_1532072965009']").click(function(){
		/**--执行方法体-start--******/
			window.close();
		/**--执行方法体-end--******/
	});
}catch(e){}
/**--单击事件备注信息--******/
try{
	$("[id='botton_1532074255042']").click(function(){
		/**--执行方法体-start--******/
			$.saveData(true);
		/**--执行方法体-end--******/
	});
}catch(e){}
/**--单击事件备注信息--******/
try{
	$("[id='botton_1532075935341']").click(function(){
		/**--执行方法体-start--******/
			window.close();
		/**--执行方法体-end--******/
	});
}catch(e){}
