package com.tj720.admin.model;

import java.util.Date;

public class MipModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_module.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_module.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_module.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_module.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_module.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_module.url
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_module.canDelete
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte candelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_module.remark
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_module.userId
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_module.projectId
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_module.templateId
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String templateid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_module.id
     *
     * @return the value of mip_module.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_module.id
     *
     * @param id the value for mip_module.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_module.name
     *
     * @return the value of mip_module.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_module.name
     *
     * @param name the value for mip_module.name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_module.createTime
     *
     * @return the value of mip_module.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_module.createTime
     *
     * @param createtime the value for mip_module.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_module.status
     *
     * @return the value of mip_module.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_module.status
     *
     * @param status the value for mip_module.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_module.sequence
     *
     * @return the value of mip_module.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_module.sequence
     *
     * @param sequence the value for mip_module.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_module.url
     *
     * @return the value of mip_module.url
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_module.url
     *
     * @param url the value for mip_module.url
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_module.canDelete
     *
     * @return the value of mip_module.canDelete
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getCandelete() {
        return candelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_module.canDelete
     *
     * @param candelete the value for mip_module.canDelete
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCandelete(Byte candelete) {
        this.candelete = candelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_module.remark
     *
     * @return the value of mip_module.remark
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_module.remark
     *
     * @param remark the value for mip_module.remark
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_module.userId
     *
     * @return the value of mip_module.userId
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_module.userId
     *
     * @param userid the value for mip_module.userId
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_module.projectId
     *
     * @return the value of mip_module.projectId
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_module.projectId
     *
     * @param projectid the value for mip_module.projectId
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_module.templateId
     *
     * @return the value of mip_module.templateId
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_module.templateId
     *
     * @param templateid the value for mip_module.templateId
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setTemplateid(String templateid) {
        this.templateid = templateid == null ? null : templateid.trim();
    }
}