package com.tj720.admin.dao.map;

import com.tj720.admin.model.MipCollectionResidueLevel;
import com.tj720.admin.model.MipCollectionResidueLevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MipCollectionResidueLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_collection_residue_level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int countByExample(MipCollectionResidueLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_collection_residue_level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByExample(MipCollectionResidueLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_collection_residue_level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_collection_residue_level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insert(MipCollectionResidueLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_collection_residue_level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insertSelective(MipCollectionResidueLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_collection_residue_level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipCollectionResidueLevel> selectByExample(MipCollectionResidueLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_collection_residue_level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    MipCollectionResidueLevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_collection_residue_level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") MipCollectionResidueLevel record, @Param("example") MipCollectionResidueLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_collection_residue_level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExample(@Param("record") MipCollectionResidueLevel record, @Param("example") MipCollectionResidueLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_collection_residue_level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeySelective(MipCollectionResidueLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_collection_residue_level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKey(MipCollectionResidueLevel record);
}