package com.tj720.admin.dao.map;

import com.tj720.admin.base.dao.BaseDao;
import com.tj720.admin.model.DcVersionContent;
import com.tj720.admin.model.DcVersionSelect;
import com.tj720.admin.model.DcVersionSelectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DcVersionSelectMapper extends BaseDao<DcVersionSelect>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_version_select
     *
     * @mbggenerated Fri Dec 08 13:25:01 CST 2017
     */
    int countByExample(DcVersionSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_version_select
     *
     * @mbggenerated Fri Dec 08 13:25:01 CST 2017
     */
    int deleteByExample(DcVersionSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_version_select
     *
     * @mbggenerated Fri Dec 08 13:25:01 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_version_select
     *
     * @mbggenerated Fri Dec 08 13:25:01 CST 2017
     */
    int insert(DcVersionSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_version_select
     *
     * @mbggenerated Fri Dec 08 13:25:01 CST 2017
     */
    int insertSelective(DcVersionSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_version_select
     *
     * @mbggenerated Fri Dec 08 13:25:01 CST 2017
     */
    List<DcVersionSelect> selectByExample(DcVersionSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_version_select
     *
     * @mbggenerated Fri Dec 08 13:25:01 CST 2017
     */
    DcVersionSelect selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_version_select
     *
     * @mbggenerated Fri Dec 08 13:25:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") DcVersionSelect record, @Param("example") DcVersionSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_version_select
     *
     * @mbggenerated Fri Dec 08 13:25:01 CST 2017
     */
    int updateByExample(@Param("record") DcVersionSelect record, @Param("example") DcVersionSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_version_select
     *
     * @mbggenerated Fri Dec 08 13:25:01 CST 2017
     */
    int updateByPrimaryKeySelective(DcVersionSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_version_select
     *
     * @mbggenerated Fri Dec 08 13:25:01 CST 2017
     */
    int updateByPrimaryKey(DcVersionSelect record);
}