package com.tj720.admin.dao.map;

import com.tj720.admin.model.GmCollectionRepairList;
import com.tj720.admin.model.GmCollectionRepairListExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface GmCollectionRepairListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_collection_repair_list
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int countByExample(GmCollectionRepairListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_collection_repair_list
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int deleteByExample(GmCollectionRepairListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_collection_repair_list
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_collection_repair_list
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int insert(GmCollectionRepairList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_collection_repair_list
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int insertSelective(GmCollectionRepairList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_collection_repair_list
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    List<GmCollectionRepairList> selectByExample(GmCollectionRepairListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_collection_repair_list
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    GmCollectionRepairList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_collection_repair_list
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") GmCollectionRepairList record, @Param("example") GmCollectionRepairListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_collection_repair_list
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int updateByExample(@Param("record") GmCollectionRepairList record, @Param("example") GmCollectionRepairListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_collection_repair_list
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int updateByPrimaryKeySelective(GmCollectionRepairList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_collection_repair_list
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int updateByPrimaryKey(GmCollectionRepairList record);

	void deleteByReportUploadId(String id);

	void insertBatch(List<GmCollectionRepairList> list);
}