package com.tj720.admin.dao.map;

import com.tj720.admin.model.GmEquipmentRepairSituation;
import com.tj720.admin.model.GmEquipmentRepairSituationExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface GmEquipmentRepairSituationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_equipment_repair_situation
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int countByExample(GmEquipmentRepairSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_equipment_repair_situation
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int deleteByExample(GmEquipmentRepairSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_equipment_repair_situation
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_equipment_repair_situation
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int insert(GmEquipmentRepairSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_equipment_repair_situation
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int insertSelective(GmEquipmentRepairSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_equipment_repair_situation
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    List<GmEquipmentRepairSituation> selectByExample(GmEquipmentRepairSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_equipment_repair_situation
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    GmEquipmentRepairSituation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_equipment_repair_situation
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") GmEquipmentRepairSituation record, @Param("example") GmEquipmentRepairSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_equipment_repair_situation
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int updateByExample(@Param("record") GmEquipmentRepairSituation record, @Param("example") GmEquipmentRepairSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_equipment_repair_situation
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int updateByPrimaryKeySelective(GmEquipmentRepairSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gm_equipment_repair_situation
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    int updateByPrimaryKey(GmEquipmentRepairSituation record);

	void deleteByReportUploadId(String id);

	void insertBatch(List<GmEquipmentRepairSituation> list);
}