package com.tj720.admin.dao.map;

import com.tj720.admin.model.MipActivity;
import com.tj720.admin.model.MipActivityExample;
import com.tj720.mip.dto.ActivityDto;
import com.tj720.mip.dto.FullTextSearchDto;

import java.util.Date;
import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MipActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    int countByExample(MipActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    int deleteByExample(MipActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    int insert(MipActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    int insertSelective(MipActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    List<MipActivity> selectByExampleWithBLOBs(MipActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    List<MipActivity> selectByExample(MipActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    MipActivity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") MipActivity record, @Param("example") MipActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") MipActivity record, @Param("example") MipActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    int updateByExample(@Param("record") MipActivity record, @Param("example") MipActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    int updateByPrimaryKeySelective(MipActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(MipActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_activity
     *
     * @mbggenerated Fri Jul 13 13:14:01 CST 2018
     */
    int updateByPrimaryKey(MipActivity record);
	
  //根据类型查询活动列表
    List<HashMap> getActivityListByType(@Param("activityCategory") String activityCategory,@Param("orgid") String orgid,@Param("startRow") int startRow,@Param("pageSize") Integer pageSize);
    
    Integer countActivityListByType(@Param("activityCategory") String activityCategory,@Param("orgid") String orgid);
    //根据ID查询活动详情
    HashMap getActivityListById(@Param("activityId") String activityId);
    
    
    
    //后台接口
    List<ActivityDto> getActivityList(@Param("orgList")List<String> orgList, @Param("key")String key, @Param("type")String type,@Param("status")String status,@Param("startTime")String startTime,@Param("endTime")String endTime,
    		@Param("startRow") int startRow,@Param("pageSize") Integer pageSize, @Param("currentOrg")String currentOrg);

	int countActivityList(@Param("orgList")List<String> orgList, @Param("key")String key, @Param("type")String type,@Param("status")String status,@Param("startTime")String startTime,@Param("endTime")String endTime, @Param("currentOrg")String currentOrg);

	int publish(@Param("id")String id, @Param("status")String status, @Param("userId")String userId,@Param("publishTime")Date publishTime);

	//全文检索
	List<FullTextSearchDto> fullTextSearch(@Param("key")String key, @Param("type")String type,@Param("startRow")int startRow, @Param("pageSize")Integer pageSize);
	Integer countFullTextSearch(@Param("key")String key, @Param("type")String type);
		
}