package com.tj720.admin.dao.map;

import com.tj720.admin.base.dao.BaseDao;
import com.tj720.admin.model.MipBaseCulturalrelicInfo;
import com.tj720.admin.model.MipBaseCulturalrelicInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MipBaseCulturalrelicInfoMapper extends BaseDao<MipBaseCulturalrelicInfo>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_base_culturalrelic_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int countByExample(MipBaseCulturalrelicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_base_culturalrelic_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByExample(MipBaseCulturalrelicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_base_culturalrelic_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_base_culturalrelic_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insert(MipBaseCulturalrelicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_base_culturalrelic_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insertSelective(MipBaseCulturalrelicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_base_culturalrelic_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipBaseCulturalrelicInfo> selectByExample(MipBaseCulturalrelicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_base_culturalrelic_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    MipBaseCulturalrelicInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_base_culturalrelic_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") MipBaseCulturalrelicInfo record, @Param("example") MipBaseCulturalrelicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_base_culturalrelic_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExample(@Param("record") MipBaseCulturalrelicInfo record, @Param("example") MipBaseCulturalrelicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_base_culturalrelic_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeySelective(MipBaseCulturalrelicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_base_culturalrelic_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKey(MipBaseCulturalrelicInfo record);
}