package com.tj720.admin.dao.map;

import com.tj720.admin.model.MipCuration;
import com.tj720.admin.model.MipCurationExample;
import com.tj720.admin.model.MipCurationWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MipCurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int countByExample(MipCurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByExample(MipCurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insert(MipCurationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insertSelective(MipCurationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipCurationWithBLOBs> selectByExampleWithBLOBs(MipCurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipCuration> selectByExample(MipCurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    MipCurationWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") MipCurationWithBLOBs record, @Param("example") MipCurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") MipCurationWithBLOBs record, @Param("example") MipCurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExample(@Param("record") MipCuration record, @Param("example") MipCurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeySelective(MipCurationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(MipCurationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_curation
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKey(MipCuration record);
}