package com.tj720.admin.dao.map;

import com.tj720.admin.dto.MipSearchDto;
import com.tj720.admin.model.MipSearch;
import com.tj720.admin.model.MipSearchExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MipSearchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_search
     *
     * @mbggenerated Thu Aug 23 17:49:17 CST 2018
     */
    int countByExample(MipSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_search
     *
     * @mbggenerated Thu Aug 23 17:49:17 CST 2018
     */
    int deleteByExample(MipSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_search
     *
     * @mbggenerated Thu Aug 23 17:49:17 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_search
     *
     * @mbggenerated Thu Aug 23 17:49:17 CST 2018
     */
    int insert(MipSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_search
     *
     * @mbggenerated Thu Aug 23 17:49:17 CST 2018
     */
    int insertSelective(MipSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_search
     *
     * @mbggenerated Thu Aug 23 17:49:17 CST 2018
     */
    List<MipSearch> selectByExample(MipSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_search
     *
     * @mbggenerated Thu Aug 23 17:49:17 CST 2018
     */
    MipSearch selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_search
     *
     * @mbggenerated Thu Aug 23 17:49:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") MipSearch record, @Param("example") MipSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_search
     *
     * @mbggenerated Thu Aug 23 17:49:17 CST 2018
     */
    int updateByExample(@Param("record") MipSearch record, @Param("example") MipSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_search
     *
     * @mbggenerated Thu Aug 23 17:49:17 CST 2018
     */
    int updateByPrimaryKeySelective(MipSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_search
     *
     * @mbggenerated Thu Aug 23 17:49:17 CST 2018
     */
    int updateByPrimaryKey(MipSearch record);

    List<MipSearchDto> getMyQuery(@Param("userId")String userId,@Param("type")String type);
    List<MipSearchDto> getOtherQuery(@Param("userId")String userId,@Param("orgId")String orgId,@Param("type")String type);
    String getSqlByUnique(@Param("uniqueName")String uniqueName);
    String getSqlById(@Param("id")String id);
    List<Map<String, Object>> query(@Param("sqlstr")String sqlstr);
}