package com.tj720.admin.dao.map;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.tj720.admin.base.dao.BaseDao;
import com.tj720.admin.dto.MipTopicCollectionDto;
import com.tj720.admin.model.MipTopic;
import com.tj720.admin.model.MipTopicCollection;
import com.tj720.admin.model.MipTopicCollectionExample;

public interface MipTopicCollectionMapper  extends BaseDao<MipTopicCollection> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int countByExample(MipTopicCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int deleteByExample(MipTopicCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int insert(MipTopicCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int insertSelective(MipTopicCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    List<MipTopicCollection> selectByExample(MipTopicCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    MipTopicCollection selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") MipTopicCollection record, @Param("example") MipTopicCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int updateByExample(@Param("record") MipTopicCollection record, @Param("example") MipTopicCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int updateByPrimaryKeySelective(MipTopicCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic_collection
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int updateByPrimaryKey(MipTopicCollection record);
    
    List<MipTopicCollectionDto> selectListByTopicId(@Param("topicId") String topicId);

	int getMaxSort(@Param("topicId") String topicId);
	
	int batchSave(@Param("list") List<MipTopicCollection> list);
	
	List<MipTopic> selectTopicByCollection(@Param("collectionId") String collectionId);
	
	HashMap<String,Object> getCollectionTopicById(@Param("id") String id);
	
	int deleteMipTopicCollection(@Param("record") MipTopicCollection record);
	
	int deleteByCollectionId(@Param("collectionId") List<String> collectionIds);
	
	/**
	 * 根据多个专题id，获取藏品列表
	 * @param topicIds
	 * @return
	 */
	List<MipTopicCollectionDto> getListByTopicIds(@Param("topicIds") List<String> topicIds);
}