package com.tj720.admin.dao.map;

import com.tj720.admin.model.MipVirtualExibitionHall;
import com.tj720.admin.model.MipVirtualExibitionHallExample;
import com.tj720.mip.dto.VirtualDto;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MipVirtualExibitionHallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int countByExample(MipVirtualExibitionHallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByExample(MipVirtualExibitionHallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insert(MipVirtualExibitionHall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insertSelective(MipVirtualExibitionHall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipVirtualExibitionHall> selectByExampleWithBLOBs(MipVirtualExibitionHallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipVirtualExibitionHall> selectByExample(MipVirtualExibitionHallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    MipVirtualExibitionHall selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") MipVirtualExibitionHall record, @Param("example") MipVirtualExibitionHallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") MipVirtualExibitionHall record, @Param("example") MipVirtualExibitionHallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExample(@Param("record") MipVirtualExibitionHall record, @Param("example") MipVirtualExibitionHallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeySelective(MipVirtualExibitionHall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(MipVirtualExibitionHall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_virtual_exibition_hall
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKey(MipVirtualExibitionHall record);

	List<VirtualDto> getVirtualList(@Param("orgList")List<String> orgList, @Param("key")String key, @Param("type")String type
			,@Param("status")String status, @Param("startRow") int startRow,@Param("pageSize") Integer pageSize, @Param("currentOrg")String currentOrg);

	int countVirtualList(@Param("orgList")List<String> orgList, @Param("key")String key, @Param("type")String type, @Param("status")String status, @Param("currentOrg")String currentOrg);

	int publish(@Param("id")String id, @Param("status")String status, @Param("userId")String userId,@Param("publishTime")Date publishTime);
    
    
    
    
    
    
    
}