package com.tj720.admin.model;

import java.util.Date;

public class MipMuseumInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.category_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.ticket
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer ticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.ticket_price
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String ticketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.opening_hours
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String openingHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.address
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.telephone
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.city_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.f_audio
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String fAudio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.spre_open
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte spreOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.vir_open
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Byte virOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.org_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.museum_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String museumName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.click_count
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer clickCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.logo
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mip_museum_info.thin_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    private Integer thinId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.id
     *
     * @return the value of mip_museum_info.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.id
     *
     * @param id the value for mip_museum_info.id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.level
     *
     * @return the value of mip_museum_info.level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.level
     *
     * @param level the value for mip_museum_info.level
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.category_id
     *
     * @return the value of mip_museum_info.category_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.category_id
     *
     * @param categoryId the value for mip_museum_info.category_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.ticket
     *
     * @return the value of mip_museum_info.ticket
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.ticket
     *
     * @param ticket the value for mip_museum_info.ticket
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setTicket(Integer ticket) {
        this.ticket = ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.ticket_price
     *
     * @return the value of mip_museum_info.ticket_price
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getTicketPrice() {
        return ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.ticket_price
     *
     * @param ticketPrice the value for mip_museum_info.ticket_price
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setTicketPrice(String ticketPrice) {
        this.ticketPrice = ticketPrice == null ? null : ticketPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.opening_hours
     *
     * @return the value of mip_museum_info.opening_hours
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getOpeningHours() {
        return openingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.opening_hours
     *
     * @param openingHours the value for mip_museum_info.opening_hours
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setOpeningHours(String openingHours) {
        this.openingHours = openingHours == null ? null : openingHours.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.address
     *
     * @return the value of mip_museum_info.address
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.address
     *
     * @param address the value for mip_museum_info.address
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.telephone
     *
     * @return the value of mip_museum_info.telephone
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.telephone
     *
     * @param telephone the value for mip_museum_info.telephone
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.sequence
     *
     * @return the value of mip_museum_info.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.sequence
     *
     * @param sequence the value for mip_museum_info.sequence
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.status
     *
     * @return the value of mip_museum_info.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.status
     *
     * @param status the value for mip_museum_info.status
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.createTime
     *
     * @return the value of mip_museum_info.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.createTime
     *
     * @param createtime the value for mip_museum_info.createTime
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.city_id
     *
     * @return the value of mip_museum_info.city_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.city_id
     *
     * @param cityId the value for mip_museum_info.city_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.f_audio
     *
     * @return the value of mip_museum_info.f_audio
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getfAudio() {
        return fAudio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.f_audio
     *
     * @param fAudio the value for mip_museum_info.f_audio
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setfAudio(String fAudio) {
        this.fAudio = fAudio == null ? null : fAudio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.spre_open
     *
     * @return the value of mip_museum_info.spre_open
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getSpreOpen() {
        return spreOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.spre_open
     *
     * @param spreOpen the value for mip_museum_info.spre_open
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setSpreOpen(Byte spreOpen) {
        this.spreOpen = spreOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.vir_open
     *
     * @return the value of mip_museum_info.vir_open
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Byte getVirOpen() {
        return virOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.vir_open
     *
     * @param virOpen the value for mip_museum_info.vir_open
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setVirOpen(Byte virOpen) {
        this.virOpen = virOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.org_id
     *
     * @return the value of mip_museum_info.org_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.org_id
     *
     * @param orgId the value for mip_museum_info.org_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.museum_name
     *
     * @return the value of mip_museum_info.museum_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getMuseumName() {
        return museumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.museum_name
     *
     * @param museumName the value for mip_museum_info.museum_name
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setMuseumName(String museumName) {
        this.museumName = museumName == null ? null : museumName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.click_count
     *
     * @return the value of mip_museum_info.click_count
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getClickCount() {
        return clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.click_count
     *
     * @param clickCount the value for mip_museum_info.click_count
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setClickCount(Integer clickCount) {
        this.clickCount = clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.logo
     *
     * @return the value of mip_museum_info.logo
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.logo
     *
     * @param logo the value for mip_museum_info.logo
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mip_museum_info.thin_id
     *
     * @return the value of mip_museum_info.thin_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public Integer getThinId() {
        return thinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mip_museum_info.thin_id
     *
     * @param thinId the value for mip_museum_info.thin_id
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    public void setThinId(Integer thinId) {
        this.thinId = thinId;
    }
}