package com.tj720.admin.dao.map;

import com.tj720.admin.model.CulturalRelicPersonnelChange;
import com.tj720.admin.model.CulturalRelicPersonnelChangeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CulturalRelicPersonnelChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_personnel_change
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int countByExample(CulturalRelicPersonnelChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_personnel_change
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int deleteByExample(CulturalRelicPersonnelChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_personnel_change
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_personnel_change
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int insert(CulturalRelicPersonnelChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_personnel_change
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int insertSelective(CulturalRelicPersonnelChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_personnel_change
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    List<CulturalRelicPersonnelChange> selectByExample(CulturalRelicPersonnelChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_personnel_change
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    CulturalRelicPersonnelChange selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_personnel_change
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") CulturalRelicPersonnelChange record, @Param("example") CulturalRelicPersonnelChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_personnel_change
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int updateByExample(@Param("record") CulturalRelicPersonnelChange record, @Param("example") CulturalRelicPersonnelChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_personnel_change
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int updateByPrimaryKeySelective(CulturalRelicPersonnelChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_personnel_change
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int updateByPrimaryKey(CulturalRelicPersonnelChange record);

	List<CulturalRelicPersonnelChange> getPersonList(String relicsBureauId);

	int updateChangeList(List<CulturalRelicPersonnelChange> updateChangeList);

	int insertChangeList(List<CulturalRelicPersonnelChange> insertChangeList);

	List<CulturalRelicPersonnelChange> getPersonInfo(@Param("orgId") String orgId,@Param("flag") String flag);

	void deletePersonChange(@Param("orgId") String orgId,@Param("flag") String flag);

}