package com.tj720.admin.dao.map;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.tj720.admin.base.dao.BaseDao;
import com.tj720.admin.dto.MipTopicCollectionDto;
import com.tj720.admin.model.MipTopic;
import com.tj720.admin.model.MipTopicExample;

public interface MipTopicMapper extends BaseDao<MipTopic> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int countByExample(MipTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int deleteByExample(MipTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int insert(MipTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int insertSelective(MipTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    List<MipTopic> selectByExample(MipTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    MipTopic selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") MipTopic record, @Param("example") MipTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int updateByExample(@Param("record") MipTopic record, @Param("example") MipTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int updateByPrimaryKeySelective(MipTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_topic
     *
     * @mbggenerated Wed Aug 08 15:42:19 CST 2018
     */
    int updateByPrimaryKey(MipTopic record);
    
    /**
     * 根据key查询专题列表
     * @param key
     * @param status
     * @param orgId
     * @param startRow
     * @param pageSize
     * @return
     */
    List<MipTopic> selectListByKey(@Param("key") String key, @Param("status") String status, @Param("orgId") String orgId, @Param("orgIdList") List<String> orgIdList, @Param("startRow") Integer startRow, @Param("pageSize") Integer pageSize, @Param("museumId") String museumId);
    Integer countListByKey(@Param("key") String key, @Param("status") String status, @Param("orgId") String orgId, @Param("orgIdList") List<String> orgIdList, @Param("museumId") String museumId);
    
    List<MipTopic> getListByOrgId(@Param("orgId") String orgId);
    
    List<MipTopic> getListByOrgIdAndTopicId(@Param("orgId") String orgId,@Param("topicId") String topicId);
    
    List<MipTopicCollectionDto> getCollectionList(@Param("orgId") List<com.tj720.admin.model.MipOrganization> orgId, @Param("topicId") String topicId, @Param("search") MipTopicCollectionDto search, @Param("startRow") Integer startRow, @Param("pageSize") Integer pageSize);
    int countCollectionList(@Param("orgId") List<com.tj720.admin.model.MipOrganization> orgId, @Param("topicId") String topicId, @Param("search") MipTopicCollectionDto search);

}