package com.tj720.admin.dao.map;

import com.tj720.admin.model.CulturalRelicEquipmentDetail;
import com.tj720.admin.model.CulturalRelicEquipmentDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CulturalRelicEquipmentDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_equipment_detail
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int countByExample(CulturalRelicEquipmentDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_equipment_detail
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int deleteByExample(CulturalRelicEquipmentDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_equipment_detail
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_equipment_detail
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int insert(CulturalRelicEquipmentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_equipment_detail
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int insertSelective(CulturalRelicEquipmentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_equipment_detail
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    List<CulturalRelicEquipmentDetail> selectByExample(CulturalRelicEquipmentDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_equipment_detail
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    CulturalRelicEquipmentDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_equipment_detail
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") CulturalRelicEquipmentDetail record, @Param("example") CulturalRelicEquipmentDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_equipment_detail
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int updateByExample(@Param("record") CulturalRelicEquipmentDetail record, @Param("example") CulturalRelicEquipmentDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_equipment_detail
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int updateByPrimaryKeySelective(CulturalRelicEquipmentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cultural_relic_equipment_detail
     *
     * @mbggenerated Fri Aug 17 10:45:58 CST 2018
     */
    int updateByPrimaryKey(CulturalRelicEquipmentDetail record);
    /**
     * 根据组织机构ID查询
     * @param orgId
     * @return
     */
    List<CulturalRelicEquipmentDetail> getByOrgId(@Param("orgId") String orgId,@Param("flag") String flag);
}