package com.tj720.admin.dao.map;

import com.tj720.admin.model.MipLishijilinArticleCategory;
import com.tj720.admin.model.MipLishijilinArticleCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MipLishijilinArticleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_lishijilin_article_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int countByExample(MipLishijilinArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_lishijilin_article_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByExample(MipLishijilinArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_lishijilin_article_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_lishijilin_article_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insert(MipLishijilinArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_lishijilin_article_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insertSelective(MipLishijilinArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_lishijilin_article_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipLishijilinArticleCategory> selectByExample(MipLishijilinArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_lishijilin_article_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    MipLishijilinArticleCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_lishijilin_article_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") MipLishijilinArticleCategory record, @Param("example") MipLishijilinArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_lishijilin_article_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExample(@Param("record") MipLishijilinArticleCategory record, @Param("example") MipLishijilinArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_lishijilin_article_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeySelective(MipLishijilinArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_lishijilin_article_category
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKey(MipLishijilinArticleCategory record);
}