package com.tj720.admin.dao.map;

import com.tj720.admin.base.dao.BaseDao;
import com.tj720.admin.model.MipOpenFossilInfo;
import com.tj720.admin.model.MipOpenFossilInfoExample;
import com.tj720.admin.model.MipOpenFossilInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MipOpenFossilInfoMapper extends BaseDao<MipOpenFossilInfo>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int countByExample(MipOpenFossilInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByExample(MipOpenFossilInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insert(MipOpenFossilInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insertSelective(MipOpenFossilInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipOpenFossilInfoWithBLOBs> selectByExampleWithBLOBs(MipOpenFossilInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipOpenFossilInfo> selectByExample(MipOpenFossilInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    MipOpenFossilInfoWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") MipOpenFossilInfoWithBLOBs record, @Param("example") MipOpenFossilInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") MipOpenFossilInfoWithBLOBs record, @Param("example") MipOpenFossilInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExample(@Param("record") MipOpenFossilInfo record, @Param("example") MipOpenFossilInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeySelective(MipOpenFossilInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(MipOpenFossilInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_open_fossil_info
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKey(MipOpenFossilInfo record);
}