package com.tj720.admin.model;

public class GmEmployeeTrainSituation {
	
	private String num;
	
    public String getNum() {
		return num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_employee_train_situation.id
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_employee_train_situation.report_upload_id
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String reportUploadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_employee_train_situation.activity_name
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_employee_train_situation.main_content
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String mainContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_employee_train_situation.train_type
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String trainType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_employee_train_situation.start_end_time
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String startEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_employee_train_situation.place
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_employee_train_situation.people_count
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    private String peopleCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_employee_train_situation.id
     *
     * @return the value of gm_employee_train_situation.id
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_employee_train_situation.id
     *
     * @param id the value for gm_employee_train_situation.id
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_employee_train_situation.report_upload_id
     *
     * @return the value of gm_employee_train_situation.report_upload_id
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getReportUploadId() {
        return reportUploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_employee_train_situation.report_upload_id
     *
     * @param reportUploadId the value for gm_employee_train_situation.report_upload_id
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setReportUploadId(String reportUploadId) {
        this.reportUploadId = reportUploadId == null ? null : reportUploadId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_employee_train_situation.activity_name
     *
     * @return the value of gm_employee_train_situation.activity_name
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_employee_train_situation.activity_name
     *
     * @param activityName the value for gm_employee_train_situation.activity_name
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_employee_train_situation.main_content
     *
     * @return the value of gm_employee_train_situation.main_content
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getMainContent() {
        return mainContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_employee_train_situation.main_content
     *
     * @param mainContent the value for gm_employee_train_situation.main_content
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setMainContent(String mainContent) {
        this.mainContent = mainContent == null ? null : mainContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_employee_train_situation.train_type
     *
     * @return the value of gm_employee_train_situation.train_type
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getTrainType() {
        return trainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_employee_train_situation.train_type
     *
     * @param trainType the value for gm_employee_train_situation.train_type
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setTrainType(String trainType) {
        this.trainType = trainType == null ? null : trainType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_employee_train_situation.start_end_time
     *
     * @return the value of gm_employee_train_situation.start_end_time
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getStartEndTime() {
        return startEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_employee_train_situation.start_end_time
     *
     * @param startEndTime the value for gm_employee_train_situation.start_end_time
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setStartEndTime(String startEndTime) {
        this.startEndTime = startEndTime == null ? null : startEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_employee_train_situation.place
     *
     * @return the value of gm_employee_train_situation.place
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_employee_train_situation.place
     *
     * @param place the value for gm_employee_train_situation.place
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_employee_train_situation.people_count
     *
     * @return the value of gm_employee_train_situation.people_count
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public String getPeopleCount() {
        return peopleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_employee_train_situation.people_count
     *
     * @param peopleCount the value for gm_employee_train_situation.people_count
     *
     * @mbggenerated Wed Apr 11 14:08:20 CST 2018
     */
    public void setPeopleCount(String peopleCount) {
        this.peopleCount = peopleCount == null ? null : peopleCount.trim();
    }
}