package com.tj720.admin.dao.map;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.tj720.admin.base.dao.BaseDao;
import com.tj720.admin.model.GovNotice;
import com.tj720.admin.model.GovNoticeExample;

public interface GovNoticeMapper extends BaseDao<GovNotice>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    int countByExample(GovNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    int deleteByExample(GovNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    int insert(GovNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    int insertSelective(GovNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    List<GovNotice> selectByExampleWithBLOBs(GovNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    List<GovNotice> selectByExample(GovNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    GovNotice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") GovNotice record, @Param("example") GovNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") GovNotice record, @Param("example") GovNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    int updateByExample(@Param("record") GovNotice record, @Param("example") GovNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    int updateByPrimaryKeySelective(GovNotice record);
    
    int updateByPrimaryKeySelectiveOutDeadlineTime(GovNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(GovNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_notice
     *
     * @mbggenerated Mon Jul 02 15:29:53 CST 2018
     */
    int updateByPrimaryKey(GovNotice record);
    
    List<Map<String, Object>> selectReport(@Param("item") String item, @Param("name") String name, @Param("orgId") String orgId);
    
    Map<String, Object> selectReportById(@Param("id") String id);
    
    List<GovNotice> selectListByOrgId(@Param("orgId") String orgId);
    
    List<GovNotice> getList(@Param("data") Map<String, Object> data);
    int countList(@Param("data") Map<String, Object> data);
}