package com.tj720.mip.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import com.tj720.mip.framework.base.BaseModel;

/**
 * MipCollect generated by hbm2java
 */
@Entity
@Table(name = "mip_collect")
@GenericGenerator(name="Generator", strategy="com.tj720.mip.framework.IdGenerator")
public class MipCollect extends BaseModel implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private String uid;
	private String cid;
	private String fid;

	public MipCollect() {
	}

	public MipCollect(String id, String uid, String cid, String fid, byte status, int sequence, String createTime) {
		this.id = id;
		this.uid = uid;
		this.cid = cid;
		this.fid = fid;
		this.status = status;
		this.sequence = sequence;
		this.createTime = createTime;
	}

	@Column(name = "uid", nullable = false, length = 50)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "cid", nullable = false, length = 50)
	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	

}
