package com.tj720.mip.model;
// Generated 2017-2-5 20:45:20 by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.core.sym.Name;
import com.tj720.mip.framework.base.BaseModel;

/**
 * MipOpenFossilInfo generated by hbm2java
 */
@Entity
@Table(name = "mip_open_fossil_info")
@GenericGenerator(name="Generator", strategy="com.tj720.mip.framework.IdGenerator")
public class MipOpenFossilInfoStatic extends BaseModel implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private String collectionUnit="";
	private String dwid="";
	private String gsNo="";
	private String fpic="";
	private int fpicWidth;
	private int fpicHeight;
	private String gsCollectionsNoType="";
	private String gsCollectionsNo="";
	private String collectionType="";
	private String name="";
	private String indexName="";
	private String formerly="";
	private String foreignName="";
	private String yearTypeEon="";
	private String yearTypeEra="";
	private String yearTypeEpoch="";
	private String yearType="";
	private String gsSpecificYear="";
	private String collectionsCategory="";
	private String gsTextureCategory="";
	private String gsTextureSubcategories="";
	private String gsTexture="";
	private String actualQuantityUnit="";
	private float actualQuantity;
	private float gsLength;
	private float gsWidth;
	private float gsHeight;
	private String size="";
	private String massRange="";
	private String mass="";
	private String massUnit="";
	private String collectionLevel="";
	private String gsSource="";
	private String collectionPlace="";
	private String endResidueLevel="";
	private String endResidualCondition="";
	private String gsStorageType="";
	private String gsStorageState="";
	private String gsEntryWarehouseTimeFrame="";
	private String gsEntryWarehouseYear="";
	private String gsEntryWarehouseTime="";
	private String gsAuthor="";
	private String gsVersion="";
	private String gsKeepOnFile="";
	private byte isHighQuality=0;
	private byte isOpen = 0;
	private byte gjOpen = 0;
	private String approvalId;
	private String description="";
	private String remark="";
	private String creator="";
	private String assessor="";
	private String fCreateDept="";
	private String fKey="";
	private String pictureId="";
	private String threeDimensionalCollection="";
	private String ringBeatData="";
	private String fVideo="";
	private String fAudio="";
	private String fMeseumId="";
	private byte checkState;
	private int clickCounts;
	private int selectCounts;
	private int collectedCounts;
	private String submitTime="";
	private int isBorrow;
	private String userName;
	private String content;
	
	
	@Transient
	public String getUserName() {
		return userName;
	}


	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Transient
	public String getContent() {
		return content;
	}


	public void setContent(String content) {
		this.content = content;
	}
	
	
	@Transient
	public int getIsBorrow() {
		return isBorrow;
	}


	public void setIsBorrow(int isBorrow) {
		this.isBorrow = isBorrow;
	}

	public MipOpenFossilInfoStatic() {
	}

	@Column(name = "collection_unit", length = 100)
	public String getCollectionUnit() {
		return this.collectionUnit;
	}

	public void setCollectionUnit(String collectionUnit) {
		this.collectionUnit = collectionUnit;
	}


	@Column(name = "dwid", length = 100)
	public String getDwid() {
		return this.dwid;
	}

	public void setDwid(String dwid) {
		this.dwid = dwid;
	}

	@Column(name = "gs_No", length = 100)
	public String getGsNo() {
		return this.gsNo;
	}

	public void setGsNo(String gsNo) {
		this.gsNo = gsNo;
	}
	
	
	@Column(name = "fPic")
	public String getFpic() {
		return fpic;
	}

	public void setFpic(String fpic) {
		this.fpic = fpic;
	}

	@Column(name = "fPic_width")
	public int getFpicWidth() {
		return fpicWidth;
	}

	public void setFpicWidth(int fpicWidth) {
		this.fpicWidth = fpicWidth;
	}

	@Column(name = "fPic_height")
	public int getFpicHeight() {
		return fpicHeight;
	}

	public void setFpicHeight(int fpicHeight) {
		this.fpicHeight = fpicHeight;
	}

	@Column(name = "gs_collectionsNo_type", length = 100)
	public String getGsCollectionsNoType() {
		return this.gsCollectionsNoType;
	}

	public void setGsCollectionsNoType(String gsCollectionsNoType) {
		this.gsCollectionsNoType = gsCollectionsNoType;
	}

	@Column(name = "gs_collectionsNo", length = 100)
	public String getGsCollectionsNo() {
		return this.gsCollectionsNo;
	}

	public void setGsCollectionsNo(String gsCollectionsNo) {
		this.gsCollectionsNo = gsCollectionsNo;
	}

	@Column(name = "collection_type", nullable = false, length = 50)
	public String getCollectionType() {
		return this.collectionType;
	}

	public void setCollectionType(String collectionType) {
		this.collectionType = collectionType;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	

	@Column(name = "index_name")
	public String getIndexName() {
		return indexName;
	}

	public void setIndexName(String indexName) {
		this.indexName = indexName;
	}

	@Column(name = "formerly", length = 100)
	public String getFormerly() {
		return this.formerly;
	}

	public void setFormerly(String formerly) {
		this.formerly = formerly;
	}

	@Column(name = "foreign_name", length = 100)
	public String getForeignName() {
		return this.foreignName;
	}

	public void setForeignName(String foreignName) {
		this.foreignName = foreignName;
	}

	@Column(name = "year_type_eon", length = 50)
	public String getYearTypeEon() {
		return this.yearTypeEon;
	}

	public void setYearTypeEon(String yearTypeEon) {
		this.yearTypeEon = yearTypeEon;
	}

	@Column(name = "year_type_era", length = 50)
	public String getYearTypeEra() {
		return this.yearTypeEra;
	}

	public void setYearTypeEra(String yearTypeEra) {
		this.yearTypeEra = yearTypeEra;
	}

	@Column(name = "year_type_epoch", length = 50)
	public String getYearTypeEpoch() {
		return this.yearTypeEpoch;
	}

	public void setYearTypeEpoch(String yearTypeEpoch) {
		this.yearTypeEpoch = yearTypeEpoch;
	}
	
	@Column(name = "year_type")
	public String getYearType() {
		return yearType;
	}

	public void setYearType(String yearType) {
		this.yearType = yearType;
	}
	
	@Column(name = "gs_specific_year", length = 100)
	public String getGsSpecificYear() {
		return this.gsSpecificYear;
	}

	public void setGsSpecificYear(String gsSpecificYear) {
		this.gsSpecificYear = gsSpecificYear;
	}

	@Column(name = "collections_category", nullable = false, length = 50)
	public String getCollectionsCategory() {
		return this.collectionsCategory;
	}

	public void setCollectionsCategory(String collectionsCategory) {
		this.collectionsCategory = collectionsCategory;
	}

	@Column(name = "gs_texture_category", length = 100)
	public String getGsTextureCategory() {
		return this.gsTextureCategory;
	}

	public void setGsTextureCategory(String gsTextureCategory) {
		this.gsTextureCategory = gsTextureCategory;
	}

	@Column(name = "gs_texture_subcategories", length = 100)
	public String getGsTextureSubcategories() {
		return this.gsTextureSubcategories;
	}

	public void setGsTextureSubcategories(String gsTextureSubcategories) {
		this.gsTextureSubcategories = gsTextureSubcategories;
	}

	@Column(name = "gs_texture", length = 100)
	public String getGsTexture() {
		return this.gsTexture;
	}

	public void setGsTexture(String gsTexture) {
		this.gsTexture = gsTexture;
	}

	@Column(name = "actual_quantity_unit", length = 100)
	public String getActualQuantityUnit() {
		return this.actualQuantityUnit;
	}

	public void setActualQuantityUnit(String actualQuantityUnit) {
		this.actualQuantityUnit = actualQuantityUnit;
	}

	@Column(name = "actual_quantity", precision = 12, scale = 0)
	public float getActualQuantity() {
		return this.actualQuantity;
	}

	public void setActualQuantity(float actualQuantity) {
		this.actualQuantity = actualQuantity;
	}

	@Column(name = "gs_length", precision = 12, scale = 0)
	public float getGsLength() {
		return this.gsLength;
	}

	public void setGsLength(float gsLength) {
		this.gsLength = gsLength;
	}

	@Column(name = "gs_width", precision = 12, scale = 0)
	public float getGsWidth() {
		return this.gsWidth;
	}

	public void setGsWidth(float gsWidth) {
		this.gsWidth = gsWidth;
	}

	@Column(name = "gs_height", precision = 12, scale = 0)
	public float getGsHeight() {
		return this.gsHeight;
	}

	public void setGsHeight(float gsHeight) {
		this.gsHeight = gsHeight;
	}

	@Column(name = "size", length = 100)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Column(name = "mass_range", length = 100)
	public String getMassRange() {
		return this.massRange;
	}

	public void setMassRange(String massRange) {
		this.massRange = massRange;
	}

	@Column(name = "mass", length = 100)
	public String getMass() {
		return this.mass;
	}

	public void setMass(String mass) {
		this.mass = mass;
	}

	@Column(name = "mass_unit", length = 100)
	public String getMassUnit() {
		return this.massUnit;
	}

	public void setMassUnit(String massUnit) {
		this.massUnit = massUnit;
	}

	@Column(name = "collection_level", length = 100)
	public String getCollectionLevel() {
		return this.collectionLevel;
	}

	public void setCollectionLevel(String collectionLevel) {
		this.collectionLevel = collectionLevel;
	}

	@Column(name = "gs_source", length = 100)
	public String getGsSource() {
		return this.gsSource;
	}

	public void setGsSource(String gsSource) {
		this.gsSource = gsSource;
	}

	@Column(name = "collection_place", length = 100)
	public String getCollectionPlace() {
		return this.collectionPlace;
	}

	public void setCollectionPlace(String collectionPlace) {
		this.collectionPlace = collectionPlace;
	}

	@Column(name = "end_residue_level", length = 100)
	public String getEndResidueLevel() {
		return this.endResidueLevel;
	}

	public void setEndResidueLevel(String endResidueLevel) {
		this.endResidueLevel = endResidueLevel;
	}

	@Column(name = "end_residual_condition", length = 100)
	public String getEndResidualCondition() {
		return this.endResidualCondition;
	}

	public void setEndResidualCondition(String endResidualCondition) {
		this.endResidualCondition = endResidualCondition;
	}

	@Column(name = "gs_storage_type", length = 100)
	public String getGsStorageType() {
		return this.gsStorageType;
	}

	public void setGsStorageType(String gsStorageType) {
		this.gsStorageType = gsStorageType;
	}

	@Column(name = "gs_storage_state", length = 100)
	public String getGsStorageState() {
		return this.gsStorageState;
	}

	public void setGsStorageState(String gsStorageState) {
		this.gsStorageState = gsStorageState;
	}

	@Column(name = "gs_entry_warehouse_time_frame", length = 100)
	public String getGsEntryWarehouseTimeFrame() {
		return this.gsEntryWarehouseTimeFrame;
	}

	public void setGsEntryWarehouseTimeFrame(String gsEntryWarehouseTimeFrame) {
		this.gsEntryWarehouseTimeFrame = gsEntryWarehouseTimeFrame;
	}

	@Column(name = "gs_entry_warehouse_year", length = 100)
	public String getGsEntryWarehouseYear() {
		return this.gsEntryWarehouseYear;
	}

	public void setGsEntryWarehouseYear(String gsEntryWarehouseYear) {
		this.gsEntryWarehouseYear = gsEntryWarehouseYear;
	}

	@Column(name = "gs_entry_warehouse_time", length = 100)
	public String getGsEntryWarehouseTime() {
		return this.gsEntryWarehouseTime;
	}

	public void setGsEntryWarehouseTime(String gsEntryWarehouseTime) {
		this.gsEntryWarehouseTime = gsEntryWarehouseTime;
	}

	@Column(name = "gs_author", length = 100)
	public String getGsAuthor() {
		return this.gsAuthor;
	}

	public void setGsAuthor(String gsAuthor) {
		this.gsAuthor = gsAuthor;
	}

	@Column(name = "gs_version", length = 100)
	public String getGsVersion() {
		return this.gsVersion;
	}

	public void setGsVersion(String gsVersion) {
		this.gsVersion = gsVersion;
	}

	@Column(name = "gs_keep_on_file", length = 100)
	public String getGsKeepOnFile() {
		return this.gsKeepOnFile;
	}

	public void setGsKeepOnFile(String gsKeepOnFile) {
		this.gsKeepOnFile = gsKeepOnFile;
	}

	@Column(name = "is_high_quality")
	public Byte getIsHighQuality() {
		return this.isHighQuality;
	}

	public void setIsHighQuality(byte isHighQuality) {
		this.isHighQuality = isHighQuality;
	}

	@Column(name = "is_open", nullable = false)
	public byte getIsOpen() {
		return this.isOpen;
	}

	public void setIsOpen(byte isOpen) {
		this.isOpen = isOpen;
	}
	
	

	/**
	 * @return the gjOpen
	 */
	@Column(name = "gj_open", nullable = false)
	public byte getGjOpen() {
		return gjOpen;
	}


	/**
	 * @param gjOpen the gjOpen to set
	 */
	public void setGjOpen(byte gjOpen) {
		this.gjOpen = gjOpen;
	}


	/**
	 * @return the approvalId
	 */
	@Column(name = "approval_id", nullable = false)
	public String getApprovalId() {
		return approvalId;
	}


	/**
	 * @param approvalId the approvalId to set
	 */
	public void setApprovalId(String approvalId) {
		this.approvalId = approvalId;
	}


	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "remark", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "creator", length = 50)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "assessor", length = 50)
	public String getAssessor() {
		return this.assessor;
	}

	public void setAssessor(String assessor) {
		this.assessor = assessor;
	}


	@Column(name = "select_counts")
	public int getSelectCounts() {
		return selectCounts;
	}

	public void setSelectCounts(int selectCounts) {
		this.selectCounts = selectCounts;
	}

	@Column(name = "f_create_dept")
	public String getfCreateDept() {
		return fCreateDept;
	}

	public void setfCreateDept(String fCreateDept) {
		this.fCreateDept = fCreateDept;
	}

	@Column(name = "f_key")
	public String getfKey() {
		return fKey;
	}

	public void setfKey(String fKey) {
		this.fKey = fKey;
	}

	@Column(name = "picture_ids")
	public String getPictureId() {
		return pictureId;
	}

	public void setPictureId(String pictureId) {
		this.pictureId = pictureId;
	}

	@Column(name="three_dimensional_collection")
	public String getThreeDimensionalCollection() {
		return threeDimensionalCollection;
	}

	public void setThreeDimensionalCollection(String threeDimensionalCollection) {
		this.threeDimensionalCollection = threeDimensionalCollection;
	}

	@Column(name="ring_beat_data")
	public String getRingBeatData() {
		return ringBeatData;
	}

	public void setRingBeatData(String ringBeatData) {
		this.ringBeatData = ringBeatData;
	}

	@Column(name="f_video")
	public String getfVideo() {
		return fVideo;
	}

	public void setfVideo(String fVideo) {
		this.fVideo = fVideo;
	}

	@Column(name = "f_audio")
	public String getfAudio() {
		return fAudio;
	}

	public void setfAudio(String fAudio) {
		this.fAudio = fAudio;
	}

	@Column(name="f_museum_id")
	public String getfMeseumId() {
		return fMeseumId;
	}

	public void setfMeseumId(String fMeseumId) {
		this.fMeseumId = fMeseumId;
	}

	@Column(name="check_state")
	public byte getCheckState() {
		return checkState;
	}
	
	public void setCheckState(byte checkState) {
		this.checkState = checkState;
	}
	

	@Column(name="click_counts")
	public int getClickCounts() {
		return clickCounts;
	}



	public void setClickCounts(int clickCounts) {

		this.clickCounts = clickCounts;
	}
	

	@Column(name="submitTime")
	public String getSubmitTime() {
		return submitTime;
	}


	public void setSubmitTime(String submitTime) {
		this.submitTime = submitTime;
	}


	@Column(name = "collected_counts")
	public int getCollectedCounts() {
		return collectedCounts;
	}

	public void setCollectedCounts(int collectedCounts) {
		this.collectedCounts = collectedCounts;
	}

	   
	/**    
	 * <pre>创建一个新的实例 MipOpenFossilInfo.    
	 *    </pre>    
	 */
	public MipOpenFossilInfoStatic(String id,String collectionType, int clickCounts) {
		super();
		this.id = id;
		this.collectionType = collectionType;
		this.clickCounts = clickCounts;
	}
	
	public MipOpenFossilInfoStatic(String id, String name, String collectionType, int clickCounts) {
		super();
		this.id = id;
		this.name = name;
		this.collectionType = collectionType;
		this.clickCounts = clickCounts;
	}
	
	
	
	
}
