package com.tj720.admin.dao.map;

import com.tj720.admin.base.dao.BaseDao;
import com.tj720.admin.model.MipStatistics;
import com.tj720.admin.model.MipStatisticsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MipStatisticsMapper extends BaseDao<MipStatistics>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_statistics
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int countByExample(MipStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_statistics
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByExample(MipStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_statistics
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_statistics
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insert(MipStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_statistics
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int insertSelective(MipStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_statistics
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    List<MipStatistics> selectByExample(MipStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_statistics
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    MipStatistics selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_statistics
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") MipStatistics record, @Param("example") MipStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_statistics
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByExample(@Param("record") MipStatistics record, @Param("example") MipStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_statistics
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKeySelective(MipStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mip_statistics
     *
     * @mbggenerated Wed Aug 09 11:14:20 CST 2017
     */
    int updateByPrimaryKey(MipStatistics record);
    
    int updateNumberOa(@Param("example") MipStatisticsExample example);
    int updateNumberOaSub(@Param("example") MipStatisticsExample example);
}