/**--单击事件备注信息--******/
try{
	$("[id='botton_1531446128363']").click(function(){
		/**--执行方法体-start--******/
			$.saveData(true);
		/**--执行方法体-end--******/
	});
}catch(e){}
/**--单击事件备注信息--******/
try{
	$("[id='botton_1531446133686']").click(function(){
		/**--执行方法体-start--******/
			window.close();
		/**--执行方法体-end--******/
	});
}catch(e){}
